apiVersion: apps/v1
kind: Deployment
metadata:
  name: UNOdemo
  labels:
    app: UNOdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: UNOdemo
  template:
    metadata:
      labels:
        app: UNOdemo
    spec:
      containers:
      - name: UNOdemo
        image: wahid1moncef/UNObackend:9
        ports:
        - containerPort: 8080